### ISSUE TITLE
Report has no options

### ISSUE THREAD

**Issue by qazokm** [thomasfedb/charlotte#2]
Report should have the following options:
- Filter Order To
- Show/Total Descendants
- Show Item Expiries

**Comment by lachiepb** [comment]
- Reports Now filter Order to (Access via link on locations page, or adding ?order_to=true to url)
- Descendants now Show.
- Descendants now Total in final row.

**Comment by qazokm** [comment]
Report options now exist but are not used

**Comment by qazokm** [comment]
Report options now work
